# Generated by Django 5.2.4 on 2025-07-06 05:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20, verbose_name='品名')),
                ('order_date', models.DateField(verbose_name='受注日')),
                ('requested_delivery_date', models.DateField(verbose_name='得意先要求納期')),
                ('number_of_orders', models.IntegerField(verbose_name='受注数量')),
                ('material_delivery_date', models.DateField(blank=True, null=True, verbose_name='材料納期')),
                ('production_completion_date', models.DateField(blank=True, null=True, verbose_name='生産完了予定日')),
                ('shipping_date', models.DateField(blank=True, null=True, verbose_name='出荷日')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='納入日')),
                ('vehicle_dispatch', models.CharField(blank=True, choices=[('done', '完了'), ('not_done', '未了')], max_length=10, null=True, verbose_name='配車状況')),
                ('stock_quantity', models.IntegerField(blank=True, default=50000, null=True, verbose_name='在庫数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
