# Generated by Django 5.2.4 on 2025-07-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juchu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='material_delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stock_quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=20, verbose_name='製品名'),
        ),
        migrations.AlterField(
            model_name='order',
            name='requested_delivery_date',
            field=models.DateField(verbose_name='希望納期'),
        ),
    ]
